config/routes.rb
Blog::Application.routes.draw do
  get "home/index"

  resources :posts do
    resources :comments
  end

  root 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base

  has_many :comments
  validates :title, :body, presence: true
    # validates_presence_of :title, :body 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find params[:post_id]
    @comment = @post.comments.build
  end

  def create
    @post = Post.find params[:post_id]
    @comment = @post.comments.build comment_params
    if @comment.save
      redirect_to @post, notice: 'Got your comment, Dude!'
    else
      render :new   
    end 
  end

private

  def comment_params
    params.require(:comment).permit(:name, :body)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/new.html.slim
h3 = "Add Comment for #{@post.title}"
= form_for [@post, @comment] do |f|
  - if @comment.errors.any?
    #error_explanation
      h4 = "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      ul
        - @comment.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :body
    = f.text_area :body
  .actions 
    = f.submit(@comment.new_record? ? 'Create' : 'Update', class: 'btn btn-primary')

app/views/home/index.html.slim
h1 Home#index
p = link_to "view my posts", posts_path
p Find me in app/views/home/index.html.slim

app/views/layouts/application.html.slim
DOCTYPE html
html
  head
    title Blog
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  body
    .container
      - if flash[:notice]
        .alert.alert-warn= flash[:notice]
      - if flash[:alert]
        .alert.alert-error= flash[:alert]
        
      = yield

app/views/posts/_form.html.slim
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      h4 = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      ul
        - @post.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .actions 
    = f.submit(@post.new_record? ? 'Create' : 'Update', class: 'btn btn-primary')

app/views/posts/edit.html.slim
h1 Editing post

== render 'form'

= link_to 'Show', @post
'|
= link_to 'Back', posts_path

app/views/posts/index.html.slim
h1 Listing posts

table.table.table-striped
  tr
    th Title
    th Body
    th
    th
    th

  - @posts.each do |post|
    tr
      td = link_to post.title, post
      td = truncate(post.body, :length => 50) 
      td = link_to edit_post_path(post) do
        i.icon-pencil
        | edit
      td = link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Post', new_post_path, class: 'btn btn-primary'

app/views/posts/new.html.slim
h1 New post

== render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.slim
h1 = @post.title

/ p
/   strong Body:
/   = @post.body

= simple_format @post.body
=' link_to 'Add a Comment', new_post_comment_path(@post)
'|
= link_to 'Edit', edit_post_path(@post)
'|
= link_to 'Back', posts_path


h3 Comments

/ table.table.table-striped
/   tr
/     th Name
/     th Comment
/   - @comments.each do |comment|
/     tr
/       td = comment.name
/       td = comment.body

- @comments.each do |comment|
  p
    strong = comment.name
  p = comment.body
  hr
Hide full text